// Copyright 2020 ETH Zurich and University of Bologna.
// Solderpad Hardware License, Version 0.51, see LICENSE for details.
// SPDX-License-Identifier: SHL-0.51

// Author: Florian Zaruba <zarubaf@iis.ee.ethz.ch>
// Author: Fabian Schuiki <fschuiki@iis.ee.ethz.ch>
//
// AUTOMATICALLY GENERATED by genoccamy.py; edit the script instead.

<%
  cuts_soc_to_router = occamy_cfg["cuts"]["soc_to_router"]
  cuts_router_to_soc = occamy_cfg["cuts"]["router_to_soc"]
  cuts_narrow_to_quad = occamy_cfg["cuts"]["narrow_to_quad"]
  cuts_quad_to_narrow = occamy_cfg["cuts"]["quad_to_narrow"]
  cuts_wide_to_quad = occamy_cfg["cuts"]["wide_to_quad"]
  cuts_quad_to_wide = occamy_cfg["cuts"]["quad_to_wide"]
  cuts_narrow_to_cva6 = occamy_cfg["cuts"]["narrow_to_cva6"]
  cuts_narrow_conv_to_spm_narrow_pre = occamy_cfg["cuts"]["narrow_conv_to_spm_narrow_pre"]
  cuts_narrow_conv_to_spm_narrow = occamy_cfg["cuts"]["narrow_conv_to_spm_narrow"]
  cuts_narrow_and_wide = occamy_cfg["cuts"]["narrow_and_wide"]
  cuts_wide_to_hemaia_mem = occamy_cfg["cuts"]["wide_to_hemaia_mem"]
  cuts_narrow_to_hemaia_mem = occamy_cfg["cuts"]["narrow_to_hemaia_mem"]
  cuts_hemaia_mem_to_wide = occamy_cfg["cuts"]["hemaia_mem_to_wide"]
  cuts_hemaia_mem_to_narrow = occamy_cfg["cuts"]["hemaia_mem_to_narrow"]
  cuts_wide_to_wide_zero_mem = occamy_cfg["cuts"]["wide_to_wide_zero_mem"]
  cuts_periph_axi_lite_narrow = occamy_cfg["cuts"]["periph_axi_lite_narrow"]
  cuts_periph_axi_lite = occamy_cfg["cuts"]["periph_axi_lite"]
  txns_narrow_and_wide = occamy_cfg["txns"]["narrow_and_wide"]
  cuts_withing_atomic_adapter_narrow = occamy_cfg["cuts"]["atomic_adapter_narrow"]
  cuts_withing_atomic_adapter_narrow_wide = occamy_cfg["cuts"]["atomic_adapter_narrow_wide"]
  max_atomics_narrow = 8
  max_atomics_wide = 8
  max_trans_atop_filter_per = 4
  max_trans_atop_filter_ser = 32
  hbi_trunc_addr_width = 40
%>

`include "common_cells/registers.svh"
`include "register_interface/typedef.svh"
`include "axi/assign.svh"
`include "idma/typedef.svh"

module ${name}_soc
  import ${name}_pkg::*;
(
  input  logic        clk_i,
  input  logic        rst_ni,

  // Accelerator clock
  input  logic [${len(occamy_cfg["clusters"])}-1:0] clk_acc_i,
  input  logic [${len(occamy_cfg["clusters"])}-1:0] rst_acc_ni,

  input  logic        test_mode_i,
  input  chip_id_t    chip_id_i,
  input  logic [${occamy_cfg["addr_width"]-1}:0] boot_addr_i,
  // Peripheral Ports (to AXI-lite Xbar)
  output  ${soc_narrow_xbar.out_periph.req_type()} periph_axi_lite_req_o,
  input   ${soc_narrow_xbar.out_periph.rsp_type()} periph_axi_lite_rsp_i,

  input   ${soc_narrow_xbar.in_periph.req_type()} periph_axi_lite_req_i,
  output  ${soc_narrow_xbar.in_periph.rsp_type()} periph_axi_lite_rsp_o,

  // Peripheral Ports (to Regbus Xbar)
  output  ${soc_narrow_xbar.out_axi_lite_narrow_periph.req_type()} periph_axi_lite_narrow_req_o,
  input   ${soc_narrow_xbar.out_axi_lite_narrow_periph.rsp_type()} periph_axi_lite_narrow_rsp_i,

  // WIDE AXI
  // Toward HeMAiA Memory System
  output ${soc_wide_xbar.out_hemaia_mem.req_type()} hemaia_mem_axi_wide_req_o,
  input  ${soc_wide_xbar.out_hemaia_mem.rsp_type()} hemaia_mem_axi_wide_rsp_i,
  // From HeMAiA Memory System
  input  ${soc_wide_xbar.in_hemaia_mem.req_type()} hemaia_mem_axi_wide_req_i,
  output ${soc_wide_xbar.in_hemaia_mem.rsp_type()} hemaia_mem_axi_wide_rsp_o,
  // Narrow AXI
  // Toward HeMAiA Memory System
  output ${soc_narrow_xbar.out_hemaia_mem.req_type()} hemaia_mem_axi_narrow_req_o,
  input  ${soc_narrow_xbar.out_hemaia_mem.rsp_type()} hemaia_mem_axi_narrow_rsp_i,
  // From HeMAiA Memory System
  input  ${soc_narrow_xbar.in_hemaia_mem.req_type()} hemaia_mem_axi_narrow_req_i,
  output ${soc_narrow_xbar.in_hemaia_mem.rsp_type()} hemaia_mem_axi_narrow_rsp_o,
% if occamy_cfg['hemaia_multichip']['single_chip'] is False: 
  // HeMAiA Multi-Chip AXI Interface
  // Chiplet Requst to Router
  output ${soc2router_bus.req_type()} soc2router_req_o,
  input  ${soc2router_bus.rsp_type()} soc2router_rsp_i,
  // Router Requst to Chiplet
  input  ${router2soc_bus.req_type()} router2soc_req_i,
  output ${router2soc_bus.rsp_type()} router2soc_rsp_o,
% endif

  // SoC control register IO
  output logic [1:0] spm_narrow_rerror_o,
  output logic [1:0] spm_wide_rerror_o,

  // Interrupts and debug requests
  input  logic [${cores-1}:0] mtip_i,
  input  logic [${cores-1}:0] msip_i,
  input  logic [1:0] eip_i,
  input  logic [0:0] debug_req_i,

  /// SRAM configuration
  input sram_cfgs_t sram_cfgs_i
);


  ///////////////
  // Crossbars //
  ///////////////

  ${module}

% if occamy_cfg['hemaia_multichip']['single_chip'] is False: 
  ///////////////////////////////////////
  // Connections between SoC to Router //
  ///////////////////////////////////////
  <% 
    soc2router = soc_wide_xbar.out_hemaia_multichip \
                              .change_iw(context, soc2router_bus.iw, "soc2router_iwc",max_txns_per_id=txns_narrow_and_wide) \
                              .cut(context, cuts_soc_to_router, name="soc2router_cut")
    router2soc = router2soc_bus.copy(name="router2soc") \
                               .declare(context)
    router2soc.cut(context, cuts_router_to_soc, name="router2soc_cut") \
              .change_iw(context, soc_wide_xbar.in_hemaia_multichip.iw, name="router2soc_iwc", to=soc_wide_xbar.in_hemaia_multichip, max_txns_per_id=txns_narrow_and_wide)
  %> \
  assign soc2router_req_o = ${soc2router.req_name()};
  assign ${soc2router.rsp_name()} = soc2router_rsp_i;
  assign ${router2soc.req_name()} = router2soc_req_i;
  assign router2soc_rsp_o = ${router2soc.rsp_name()};
% endif

  ///////////////////////////////////
  // Connections between crossbars //
  ///////////////////////////////////
  <%
    #// narrow xbar -> wide xbar & wide xbar -> narrow xbar
    soc_narrow_xbar.out_soc_wide \
      .atomic_adapter(context, max_trans=max_atomics_wide, user_as_id=1, user_id_msb=soc_narrow_xbar.out_soc_wide.uw-1, user_id_lsb=0, n_cuts= cuts_withing_atomic_adapter_narrow_wide, name="soc_narrow_wide_amo_adapter") \
      .cut(context, cuts_narrow_and_wide) \
      .change_iw(context, soc_wide_xbar.in_soc_narrow.iw, "soc_narrow_wide_iwc", max_txns_per_id=txns_narrow_and_wide) \
      .change_uw(context, soc_wide_xbar.in_soc_narrow.uw, "soc_narrow_wide_uwc") \
      .change_dw(context, soc_wide_xbar.in_soc_narrow.dw, "soc_narrow_wide_dw", to=soc_wide_xbar.in_soc_narrow)
    soc_wide_xbar.out_soc_narrow \
      .change_iw(context, soc_narrow_xbar.in_soc_wide.iw, "soc_wide_narrow_iwc", max_txns_per_id=txns_narrow_and_wide) \
      .change_uw(context, soc_narrow_xbar.in_soc_wide.uw, "soc_wide_narrow_uwc") \
      .change_dw(context, soc_narrow_xbar.in_soc_wide.dw, "soc_wide_narrow_dw") \
      .cut(context, cuts_narrow_and_wide, to=soc_narrow_xbar.in_soc_wide)
  %>\

  //////////
  // CVA6 //
  //////////
  <%
    cva6_mst = soc_narrow_xbar.__dict__["in_cva6"].copy(name="cva6_mst").declare(context)
    cva6_mst.cut(context, cuts_narrow_to_cva6, to=soc_narrow_xbar.__dict__["in_cva6"])
  %>\

  ${name}_cva6_ara i_${name}_cva6_ara (
    .clk_i (clk_i),
    .rst_ni (rst_ni),
    .chip_id_i (chip_id_i),
    .irq_i (eip_i),
    .ipi_i (msip_i[0]),
    .time_irq_i (mtip_i[0]),
    .debug_req_i (debug_req_i[0]),
    .boot_addr_i (boot_addr_i),
    .axi_req_o (${cva6_mst.req_name()}),
    .axi_resp_i (${cva6_mst.rsp_name()})
  );

  //////////
  // Quad //
  //////////
  <%
    #// Derived parameters
    nr_cores_per_quad = nr_cores_quadrant
    lower_core =  1
    #// narrow xbar -> quad & quad -> narrow xbar
    narrow_in = soc_narrow_xbar.out_quad.cut(context, cuts_narrow_to_quad, name="narrow_in")
    narrow_out = soc_narrow_xbar.in_quad.copy(name="narrow_out").declare(context)
    narrow_out.cut(context, cuts_quad_to_narrow, name="narrow_out_cut", to=soc_narrow_xbar.in_quad)
    #// wide xbar -> quad & quad -> wide xbar
    wide_in = soc_wide_xbar.out_quad.cut(context, cuts_wide_to_quad, name="wide_in")
    wide_out = soc_wide_xbar.in_quad.copy(name="wide_out").declare(context)
    wide_out.cut(context, cuts_quad_to_wide, name="wide_out_cut", to=soc_wide_xbar.in_quad)
  %>\

  ${name}_quad i_${name}_quad (
    .clk_i (clk_i),
    .rst_ni (rst_ni),
    .clk_acc_i (clk_acc_i),
    .rst_acc_ni (rst_acc_ni),
    .test_mode_i (test_mode_i),
    .boot_addr_i (boot_addr_i[31:0]),
    .chip_id_i (chip_id_i),
    .meip_i ('0),
    .mtip_i (mtip_i[${lower_core + nr_cores_per_quad - 1}:${lower_core}]),
    .msip_i (msip_i[${lower_core + nr_cores_per_quad - 1}:${lower_core}]),
    .quadrant_narrow_out_req_o (${narrow_out.req_name()}),
    .quadrant_narrow_out_rsp_i (${narrow_out.rsp_name()}),
    .quadrant_narrow_in_req_i (${narrow_in.req_name()}),
    .quadrant_narrow_in_rsp_o (${narrow_in.rsp_name()}),
    .quadrant_wide_out_req_o (${wide_out.req_name()}),
    .quadrant_wide_out_rsp_i (${wide_out.rsp_name()}),
    .quadrant_wide_in_req_i (${wide_in.req_name()}),
    .quadrant_wide_in_rsp_o (${wide_in.rsp_name()}),
    .sram_cfg_i (sram_cfgs_i.quadrant)
  );


  ////////////////
  // SPM NARROW //
  ////////////////
  <% narrow_spm_mst = soc_narrow_xbar.out_spm_narrow \
                      .cut(context, cuts_narrow_conv_to_spm_narrow_pre) \
                      .atomic_adapter(context, max_trans=max_atomics_narrow, user_as_id=1, user_id_msb=soc_narrow_xbar.out_spm_narrow.uw-1, user_id_lsb=0, n_cuts= cuts_withing_atomic_adapter_narrow,name="spm_narrow_amo_adapter") \
                      .cut(context, cuts_narrow_conv_to_spm_narrow)
  %>\

  <% spm_narrow_words = occamy_cfg["spm_narrow"]["length"]//(soc_narrow_xbar.out_spm_narrow.dw//8) %>\

  typedef logic [${util.clog2(spm_narrow_words) + util.clog2(soc_narrow_xbar.out_spm_narrow.dw//8)-1}:0] mem_narrow_addr_t;
  typedef logic [${soc_narrow_xbar.out_spm_narrow.dw-1}:0] mem_narrow_data_t;
  typedef logic [${soc_narrow_xbar.out_spm_narrow.dw//8-1}:0] mem_narrow_strb_t;

  logic spm_narrow_req, spm_narrow_gnt, spm_narrow_we, spm_narrow_rvalid;
  mem_narrow_addr_t spm_narrow_addr;
  mem_narrow_data_t spm_narrow_wdata, spm_narrow_rdata;
  mem_narrow_strb_t spm_narrow_strb;

  axi_to_mem_interleaved #(
    .axi_req_t (${narrow_spm_mst.req_type()}),
    .axi_resp_t (${narrow_spm_mst.rsp_type()}),
    .AddrWidth (${util.clog2(spm_narrow_words) + util.clog2(narrow_spm_mst.dw//8)}),
    .DataWidth (${narrow_spm_mst.dw}),
    .IdWidth (${narrow_spm_mst.iw}),
    .NumBanks (1),
    .BufDepth (16)
  ) i_axi_to_wide_mem (
    .clk_i (${narrow_spm_mst.clk}),
    .rst_ni (${narrow_spm_mst.rst}),
    .busy_o (),
    .test_i (test_mode_i),
    .axi_req_i (${narrow_spm_mst.req_name()}),
    .axi_resp_o (${narrow_spm_mst.rsp_name()}),
    .mem_req_o (spm_narrow_req),
    .mem_gnt_i (spm_narrow_gnt),
    .mem_addr_o (spm_narrow_addr),
    .mem_wdata_o (spm_narrow_wdata),
    .mem_strb_o (spm_narrow_strb),
    .mem_atop_o (),
    .mem_we_o (spm_narrow_we),
    .mem_rvalid_i (spm_narrow_rvalid),
    .mem_rdata_i (spm_narrow_rdata)
  );

  spm_1p_adv #(
    .NumWords (${spm_narrow_words}),
    .DataWidth (${narrow_spm_mst.dw}),
    .ByteWidth (8),
    .EnableInputPipeline (1'b1),
    .EnableOutputPipeline (1'b1),
    .sram_cfg_t (sram_cfg_t)
  ) i_spm_narrow_cut (
    .clk_i (${narrow_spm_mst.clk}),
    .rst_ni (${narrow_spm_mst.rst}),
    .valid_i (spm_narrow_req),
    .ready_o (spm_narrow_gnt),
    .we_i (spm_narrow_we),
    .addr_i (spm_narrow_addr[${util.clog2(spm_narrow_words) + util.clog2(narrow_spm_mst.dw//8)-1}:${util.clog2(narrow_spm_mst.dw//8)}]),
    .wdata_i (spm_narrow_wdata),
    .be_i (spm_narrow_strb),
    .rdata_o (spm_narrow_rdata),
    .rvalid_o (spm_narrow_rvalid),
    .rerror_o (spm_narrow_rerror_o),
    .sram_cfg_i (sram_cfgs_i.spm_narrow)
  );

  
  //////////////////////////////////////
  // SoC NARROW to HeMAiA Mem System  //
  //////////////////////////////////////
  <% 
  narrow_memory_mst = soc_narrow_xbar.out_hemaia_mem \
                    .cut(context, cuts_narrow_to_hemaia_mem, name="narrow_memory_mst_cut")
  narrow_memory_slv = soc_narrow_xbar.in_hemaia_mem.copy(name="narrow_memory_slv").declare(context)
  narrow_memory_slv.cut(context, cuts_hemaia_mem_to_narrow, name="narrow_memory_slv_cut", to=soc_narrow_xbar.in_hemaia_mem)
  %>
  assign hemaia_mem_axi_narrow_req_o = ${narrow_memory_mst.req_name()};
  assign ${narrow_memory_mst.rsp_name()} = hemaia_mem_axi_narrow_rsp_i;
  assign ${narrow_memory_slv.req_name()} = hemaia_mem_axi_narrow_req_i;
  assign hemaia_mem_axi_narrow_rsp_o = ${narrow_memory_slv.rsp_name()};
  //////////////
  // SPM WIDE //
  //////////////
  <% 
  wide_memory_mst = soc_wide_xbar.out_hemaia_mem \
                    .cut(context, cuts_wide_to_hemaia_mem, name="wide_memory_mst_cut")
  wide_memory_slv = soc_wide_xbar.in_hemaia_mem.copy(name="wide_memory_slv").declare(context)
  wide_memory_slv.cut(context, cuts_hemaia_mem_to_wide, name="wide_memory_slv_cut", to=soc_wide_xbar.in_hemaia_mem)
  %>\

  assign hemaia_mem_axi_wide_req_o = ${wide_memory_mst.req_name()};
  assign ${wide_memory_mst.rsp_name()} = hemaia_mem_axi_wide_rsp_i;
  assign ${wide_memory_slv.req_name()} = hemaia_mem_axi_wide_req_i;
  assign hemaia_mem_axi_wide_rsp_o = ${wide_memory_slv.rsp_name()};

  //////////////////////
  // WIDE ZERO MEMORY //
  //////////////////////
  <% wide_zero_mem_mst = soc_wide_xbar.out_wide_zero_mem \
                         .cut(context, cuts_wide_to_wide_zero_mem)
  %>\

  <% wide_zero_mem_words = occamy_cfg["wide_zero_mem"]["length"]//(soc_wide_xbar.out_wide_zero_mem.dw//8) %>\

  axi_zero_mem #(
    .axi_req_t (${wide_zero_mem_mst.req_type()}),
    .axi_resp_t (${wide_zero_mem_mst.rsp_type()}),
    .AddrWidth (${util.clog2(wide_zero_mem_words) + util.clog2(wide_zero_mem_mst.dw//8)}),
    .DataWidth (${wide_zero_mem_mst.dw}),
    .IdWidth (${wide_zero_mem_mst.iw}),
    .NumBanks (1),
    .BufDepth (4)
  ) i_axi_wide_zero_mem (
    .clk_i (${wide_zero_mem_mst.clk}),
    .rst_ni (${wide_zero_mem_mst.rst}),
    .busy_o (),
    .axi_req_i (${wide_zero_mem_mst.req_name()}),
    .axi_resp_o (${wide_zero_mem_mst.rsp_name()})
  );

  //////////////
  // SYS iDMA //
  //////////////

  <% out_sys_idma_cfg = soc_narrow_xbar.__dict__["out_sys_idma_cfg"] \
  .atomic_adapter(context, filter=True, max_trans=max_trans_atop_filter_per, name="out_sys_idma_cfg_noatop", inst_name="i_out_sys_idma_cfg_atop_filter") \
  .change_dw(context, 32, "out_sys_idma_cfg_dw") \
  %>\

  <% in_sys_idma_mst  = soc_wide_xbar.__dict__["in_sys_idma_mst"] %>\

  // local regbus definition
  `REG_BUS_TYPEDEF_ALL(idma_cfg_reg_a${wide_in.aw}_d32, logic [${wide_in.aw-1}:0], logic [31:0], logic [3:0])

  localparam int unsigned SysIdmaTFLenWidth = ${in_sys_idma_mst.aw};

  typedef logic [${in_sys_idma_mst.aw-1}:0]   sys_idma_addr_t;
  typedef logic [${in_sys_idma_mst.iw-1}:0]   sys_idma_id_t;
  typedef logic [${in_sys_idma_mst.uw-1}:0]   sys_idma_user_t;
  typedef logic [SysIdmaTFLenWidth-1:0]       sys_idma_tf_len_t;

  // new iDMA request/response structs (explicit macros so user width = wide bus uw)
  `IDMA_TYPEDEF_OPTIONS_T(sys_idma_options_t, sys_idma_id_t)
  `IDMA_TYPEDEF_REQ_T(sys_idma_req_t, sys_idma_tf_len_t, sys_idma_addr_t, sys_idma_options_t, sys_idma_user_t)
  `IDMA_TYPEDEF_ERR_PAYLOAD_T(sys_idma_err_payload_t, sys_idma_addr_t)
  `IDMA_TYPEDEF_RSP_T(sys_idma_rsp_t, sys_idma_err_payload_t)

  // backend AXI meta channels (reuse solder-generated channel types -> guaranteed match)
  typedef struct packed { ${in_sys_idma_mst.ar_chan_type()} ar_chan; } sys_idma_axi_read_meta_t;
  typedef struct packed { sys_idma_axi_read_meta_t axi;             } sys_idma_read_meta_channel_t;
  typedef struct packed { ${in_sys_idma_mst.aw_chan_type()} aw_chan; } sys_idma_axi_write_meta_t;
  typedef struct packed { sys_idma_axi_write_meta_t axi;            } sys_idma_write_meta_channel_t;

  // 1-element regbus arrays for the NumRegs=1 frontend port
  idma_cfg_reg_a${wide_in.aw}_d32_req_t [0:0] idma_cfg_reg_req;
  idma_cfg_reg_a${wide_in.aw}_d32_rsp_t [0:0] idma_cfg_reg_rsp;

  // frontend <-> backend datapath
  sys_idma_req_t        sys_idma_req;
  logic                 sys_idma_req_valid, sys_idma_req_ready;
  sys_idma_rsp_t        sys_idma_rsp;
  logic                 sys_idma_rsp_valid;
  idma_pkg::idma_busy_t sys_idma_busy;

  // transfer-id tracking
  logic [31:0] sys_idma_next_id, sys_idma_done_id;
  logic        sys_idma_issue, sys_idma_retire;

  // backend split AXI ports (joined below)
  ${in_sys_idma_mst.req_type()} sys_idma_axi_read_req,  sys_idma_axi_write_req;
  ${in_sys_idma_mst.rsp_type()} sys_idma_axi_read_rsp,  sys_idma_axi_write_rsp;

  axi_to_reg #(
    .ADDR_WIDTH( ${out_sys_idma_cfg.aw}                 ),
    .DATA_WIDTH( ${out_sys_idma_cfg.dw}                 ),
    .ID_WIDTH  ( ${out_sys_idma_cfg.iw}                 ),
    .USER_WIDTH( ${out_sys_idma_cfg.uw}                 ),
    .axi_req_t ( ${out_sys_idma_cfg.req_type()}         ),
    .axi_rsp_t ( ${out_sys_idma_cfg.rsp_type()}         ),
    .reg_req_t ( idma_cfg_reg_a${wide_in.aw}_d32_req_t  ),
    .reg_rsp_t ( idma_cfg_reg_a${wide_in.aw}_d32_rsp_t  )
  ) i_axi_to_reg_sys_idma_cfg (
    .clk_i,
    .rst_ni,
    .testmode_i ( 1'b0                           ),
    .axi_req_i  ( ${out_sys_idma_cfg.req_name()} ),
    .axi_rsp_o  ( ${out_sys_idma_cfg.rsp_name()} ),
    .reg_req_o  ( idma_cfg_reg_req[0]            ),
    .reg_rsp_i  ( idma_cfg_reg_rsp[0]            )
  );

  idma_reg64_1d #(
    .NumRegs    ( 32'd1 ),
    .NumStreams ( 32'd1 ),
    .reg_req_t  ( idma_cfg_reg_a${wide_in.aw}_d32_req_t ),
    .reg_rsp_t  ( idma_cfg_reg_a${wide_in.aw}_d32_rsp_t ),
    .dma_req_t  ( sys_idma_req_t )
  ) i_idma_reg64_1d_sys_idma (
    .clk_i,
    .rst_ni,
    .dma_ctrl_req_i ( idma_cfg_reg_req   ),
    .dma_ctrl_rsp_o ( idma_cfg_reg_rsp   ),
    .dma_req_o      ( sys_idma_req       ),
    .req_valid_o    ( sys_idma_req_valid ),
    .req_ready_i    ( sys_idma_req_ready ),
    .next_id_i      ( sys_idma_next_id   ),
    .stream_idx_o   ( /* NC */           ),
    .done_id_i      ( sys_idma_done_id   ),
    .busy_i         ( sys_idma_busy      ),
    .midend_busy_i  ( 1'b0               )
  );

  assign sys_idma_issue  = sys_idma_req_valid & sys_idma_req_ready;
  assign sys_idma_retire = sys_idma_rsp_valid; // backend rsp_ready tied to 1

  idma_transfer_id_gen #(
    .IdWidth ( 32'd32 )
  ) i_sys_idma_transfer_id_gen (
    .clk_i,
    .rst_ni,
    .issue_i     ( sys_idma_issue   ),
    .retire_i    ( sys_idma_retire  ),
    .next_o      ( sys_idma_next_id ),
    .completed_o ( sys_idma_done_id )
  );

  idma_backend_rw_axi #(
    .DataWidth            ( ${in_sys_idma_mst.dw}         ),
    .AddrWidth            ( ${in_sys_idma_mst.aw}         ),
    .UserWidth            ( ${in_sys_idma_mst.uw}         ),
    .AxiIdWidth           ( ${in_sys_idma_mst.iw}         ),
    .NumAxInFlight        ( 32'd64                        ),
    .BufferDepth          ( 32'd3                         ),
    .TFLenWidth           ( SysIdmaTFLenWidth             ),
    .MemSysDepth          ( 32'd16                        ),
    .CombinedShifter      ( 1'b1                          ),
    .RAWCouplingAvail     ( 1'b1                          ),
    .MaskInvalidData      ( 1'b1                          ),
    .HardwareLegalizer    ( 1'b1                          ),
    .RejectZeroTransfers  ( 1'b1                          ),
    .ErrorCap             ( idma_pkg::NO_ERROR_HANDLING   ),
    .idma_req_t           ( sys_idma_req_t                ),
    .idma_rsp_t           ( sys_idma_rsp_t                ),
    .idma_eh_req_t        ( idma_pkg::idma_eh_req_t       ),
    .idma_busy_t          ( idma_pkg::idma_busy_t         ),
    .axi_req_t            ( ${in_sys_idma_mst.req_type()} ),
    .axi_rsp_t            ( ${in_sys_idma_mst.rsp_type()} ),
    .read_meta_channel_t  ( sys_idma_read_meta_channel_t  ),
    .write_meta_channel_t ( sys_idma_write_meta_channel_t )
  ) i_idma_backend_rw_axi_sys_idma (
    .clk_i,
    .rst_ni,
    .testmode_i      ( 1'b0                   ),
    .idma_req_i      ( sys_idma_req           ),
    .req_valid_i     ( sys_idma_req_valid     ),
    .req_ready_o     ( sys_idma_req_ready     ),
    .idma_rsp_o      ( sys_idma_rsp           ),
    .rsp_valid_o     ( sys_idma_rsp_valid     ),
    .rsp_ready_i     ( 1'b1                   ),
    .idma_eh_req_i   ( '0                     ),
    .eh_req_valid_i  ( 1'b0                   ),
    .eh_req_ready_o  ( /* NC */               ),
    .axi_read_req_o  ( sys_idma_axi_read_req  ),
    .axi_read_rsp_i  ( sys_idma_axi_read_rsp  ),
    .axi_write_req_o ( sys_idma_axi_write_req ),
    .axi_write_rsp_i ( sys_idma_axi_write_rsp ),
    .busy_o          ( sys_idma_busy          )
  );

  axi_rw_join #(
    .axi_req_t  ( ${in_sys_idma_mst.req_type()} ),
    .axi_resp_t ( ${in_sys_idma_mst.rsp_type()} )
  ) i_sys_idma_axi_rw_join (
    .clk_i,
    .rst_ni,
    .slv_read_req_i   ( sys_idma_axi_read_req         ),
    .slv_read_resp_o  ( sys_idma_axi_read_rsp         ),
    .slv_write_req_i  ( sys_idma_axi_write_req        ),
    .slv_write_resp_o ( sys_idma_axi_write_rsp        ),
    .mst_req_o        ( ${in_sys_idma_mst.req_name()} ),
    .mst_resp_i       ( ${in_sys_idma_mst.rsp_name()} )
  );

% if "moe_scheduler" in occamy_cfg:
  ///////////////////
  // MoE Scheduler //
  ///////////////////

  <% out_moe_scheduler = soc_narrow_xbar.__dict__["out_moe_scheduler"] \
    .atomic_adapter(context, filter=True, max_trans=max_trans_atop_filter_per,
                    name="out_moe_scheduler_noatop",
                    inst_name="i_out_moe_scheduler_atop_filter") \
  %>\

  `REG_BUS_TYPEDEF_ALL(moe_scheduler_reg_a${out_moe_scheduler.aw}_d${out_moe_scheduler.dw}, logic [${out_moe_scheduler.aw-1}:0], logic [${out_moe_scheduler.dw-1}:0], logic [${out_moe_scheduler.dw//8-1}:0])

  moe_scheduler_reg_a${out_moe_scheduler.aw}_d${out_moe_scheduler.dw}_req_t moe_scheduler_reg_req;
  moe_scheduler_reg_a${out_moe_scheduler.aw}_d${out_moe_scheduler.dw}_rsp_t moe_scheduler_reg_rsp;

  axi_to_reg #(
    .ADDR_WIDTH ( ${out_moe_scheduler.aw} ),
    .DATA_WIDTH ( ${out_moe_scheduler.dw} ),
    .ID_WIDTH   ( ${out_moe_scheduler.iw} ),
    .USER_WIDTH ( ${out_moe_scheduler.uw} ),
    .axi_req_t  ( ${out_moe_scheduler.req_type()} ),
    .axi_rsp_t  ( ${out_moe_scheduler.rsp_type()} ),
    .reg_req_t  ( moe_scheduler_reg_a${out_moe_scheduler.aw}_d${out_moe_scheduler.dw}_req_t ),
    .reg_rsp_t  ( moe_scheduler_reg_a${out_moe_scheduler.aw}_d${out_moe_scheduler.dw}_rsp_t )
  ) i_axi_to_reg_moe_scheduler (
    .clk_i,
    .rst_ni,
    .testmode_i ( 1'b0 ),
    .axi_req_i  ( ${out_moe_scheduler.req_name()} ),
    .axi_rsp_o  ( ${out_moe_scheduler.rsp_name()} ),
    .reg_req_o  ( moe_scheduler_reg_req ),
    .reg_rsp_i  ( moe_scheduler_reg_rsp )
  );

  moe_scheduler_reg_wrapper #(
    .reg_req_t ( moe_scheduler_reg_a${out_moe_scheduler.aw}_d${out_moe_scheduler.dw}_req_t ),
    .reg_rsp_t ( moe_scheduler_reg_a${out_moe_scheduler.aw}_d${out_moe_scheduler.dw}_rsp_t )
  ) i_moe_scheduler_reg_wrapper (
    .clk_i,
    .rst_ni,
    .reg_req_i ( moe_scheduler_reg_req ),
    .reg_rsp_o ( moe_scheduler_reg_rsp )
  );

% endif

  /////////////////
  // Peripherals //
  /////////////////
  <%
    periph_axi_lite_narrow_out = soc_narrow_xbar.__dict__["out_axi_lite_narrow_periph"] \
      .atomic_adapter(context, filter=True, max_trans=max_trans_atop_filter_per, name="periph_axi_lite_narrow_out_noatop", inst_name="i_periph_axi_lite_narrow_out_atop_filter") \
      .cut(context, cuts_periph_axi_lite_narrow, name="periph_axi_lite_narrow_out", inst_name="i_periph_axi_lite_narrow_out_cut")
    periph_axi_lite_out = soc_narrow_xbar.__dict__["out_periph"] \
      .atomic_adapter(context, filter=True, max_trans=max_trans_atop_filter_per, name="periph_axi_lite_out_noatop", inst_name="i_periph_axi_lite_out_atop_filter") \
      .cut(context, cuts_periph_axi_lite, name="periph_axi_lite_out", inst_name="i_periph_axi_lite_out_cut") \

    periph_axi_lite_in = soc_narrow_xbar.__dict__["in_periph"].copy(name="periph_axi_lite_in").declare(context)
    periph_axi_lite_in.cut(context, cuts_periph_axi_lite, to=soc_narrow_xbar.__dict__["in_periph"])
  %>\

  // Inputs
  assign ${periph_axi_lite_in.req_name()} = periph_axi_lite_req_i;
  assign periph_axi_lite_rsp_o = ${periph_axi_lite_in.rsp_name()};

  // Outputs
  assign periph_axi_lite_req_o = ${periph_axi_lite_out.req_name()};
  assign ${periph_axi_lite_out.rsp_name()} = periph_axi_lite_rsp_i;
  assign periph_axi_lite_narrow_req_o = ${periph_axi_lite_narrow_out.req_name()};
  assign ${periph_axi_lite_narrow_out.rsp_name()} = periph_axi_lite_narrow_rsp_i;

endmodule
